from enum import Enum


class ErrorCode(str, Enum):
    # --- AUTH ---
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"

    # --- VALIDATION ---
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AGE_TOO_LOW = "AGE_TOO_LOW"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    TERMS_REQUIRED = "TERMS_REQUIRED"

    # --- EVENTS ---
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_FULL = "EVENT_FULL"

    # --- GENERIC ---
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # --- LOGIN ---
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
