from enum import Enum


class ErrorCode(str, Enum):
    # --- AUTH ---
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"

    # --- VALIDATION ---
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AGE_TOO_LOW = "AGE_TOO_LOW"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    TERMS_REQUIRED = "TERMS_REQUIRED"

    # --- EVENTS ---
    EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
    EVENT_FULL = "EVENT_FULL"

    # --- GENERIC ---
    INTERNAL_ERROR = "INTERNAL_ERROR"
    RATE_LIMITED = "RATE_LIMITED"


    # --- LOGIN ---
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"

    EVENT_NOT_PUBLISHED = "EVENT_NOT_PUBLISHED"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    GROUP_NOT_FOUND = "GROUP_NOT_FOUND"
    GROUP_LIMIT_REACHED = "GROUP_LIMIT_REACHED"
    GROUP_CREATE_LIMIT_REACHED = "GROUP_CREATE_LIMIT_REACHED"
    ALREADY_JOINED = "ALREADY_JOINED"
    NOT_JOINED = "NOT_JOINED"
    FORBIDDEN_NOT_OWNER = "FORBIDDEN_NOT_OWNER"
    INVALID_EVENT_DATES = "INVALID_EVENT_DATES"
    INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
    INVALID_STATUS_FILTER = "INVALID_STATUS_FILTER"
    INVALID_SORT = "INVALID_SORT"
    invalid_file_type = "invalid_file_type"
    file_too_large_max_5mb = "file_too_large_max_5mb"
    age_min_must_be_lte_age_max = "age_min_must_be_lte_age_max"
    interest_too_long_max_40 = "interest_too_long_max_40"
    too_many_interests_max_20 = "too_many_interests_max_20"
