"""init

Revision ID: 1c89a100a816
Revises: 
Create Date: 2026-03-02 17:15:54.077287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c89a100a816'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_version', sa.String(length=20), nullable=True),
    sa.Column('privacy_version', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('price_fixed', sa.Integer(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=True),
    sa.Column('price_max', sa.Integer(), nullable=True),
    sa.Column('payment_link', sa.String(length=500), nullable=True),
    sa.Column('event_cover_url', sa.String(length=500), nullable=True),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 1', name='ck_events_capacity_positive'),
    sa.CheckConstraint('end_at > start_at', name='ck_events_end_after_start'),
    sa.ForeignKeyConstraint(['partner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_city_start_at', ['city', 'start_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_partner_user_id'), ['partner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_events_status_start_at', ['status', 'start_at'], unique=False)

    op.create_table('partner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=120), nullable=True),
    sa.Column('miasto', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=50), nullable=True),
    sa.Column('miasto', sa.String(length=80), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('zainteresowania_json', sa.Text(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('event_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_event_signups_event_user')
    )
    with op.batch_alter_table('event_signups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_signups_event_id'), ['event_id'], unique=False)
        batch_op.create_index('ix_event_signups_event_user', ['event_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_signups_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_signups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_signups_user_id'))
        batch_op.drop_index('ix_event_signups_event_user')
        batch_op.drop_index(batch_op.f('ix_event_signups_event_id'))

    op.drop_table('event_signups')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('partner_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_profiles_user_id'))

    op.drop_table('partner_profiles')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_status_start_at')
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_partner_user_id'))
        batch_op.drop_index('ix_events_city_start_at')

    op.drop_table('events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
