"""add_admin_display_fields

Revision ID: 485cc3af9324
Revises: 20260523_partner_plan_fields
Create Date: 2026-05-25 17:41:34.021677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485cc3af9324'
down_revision: Union[str, Sequence[str], None] = '20260523_partner_plan_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('admin_level', sa.String(length=30), nullable=True))

    op.execute(
        "UPDATE users SET admin_display_name = 'Admin Aga', admin_level = 'owner' "
        "WHERE lower(email) = 'admin@usly.dev' AND role = 'admin'"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin_level')
        batch_op.drop_column('admin_display_name')

    # ### end Alembic commands ###
