"""add friendships table

Revision ID: 91220d22ece5
Revises: cc9328369424
Create Date: 2026-03-16 18:35:37.152126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91220d22ece5'
down_revision: Union[str, Sequence[str], None] = 'cc9328369424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('addressee_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','accepted','rejected')", name='ck_friendships_status'),
    sa.CheckConstraint('requester_user_id <> addressee_user_id', name='ck_friendships_no_self'),
    sa.ForeignKeyConstraint(['addressee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_user_id', 'addressee_user_id', name='uq_friendships_requester_addressee')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index('ix_friendships_addressee_status', ['addressee_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_addressee_user_id'), ['addressee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_friendships_requester_status', ['requester_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_requester_user_id'), ['requester_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_friendships_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friendships_status'))
        batch_op.drop_index(batch_op.f('ix_friendships_requester_user_id'))
        batch_op.drop_index('ix_friendships_requester_status')
        batch_op.drop_index(batch_op.f('ix_friendships_created_at'))
        batch_op.drop_index(batch_op.f('ix_friendships_addressee_user_id'))
        batch_op.drop_index('ix_friendships_addressee_status')

    op.drop_table('friendships')
    # ### end Alembic commands ###
