"""add nearby_radius_km

Revision ID: 9ab43fe0aed9
Revises: 4bea71b0b7a2
Create Date: 2026-04-27 16:16:22.205791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab43fe0aed9'
down_revision: Union[str, Sequence[str], None] = '4bea71b0b7a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nearby_radius_km', sa.Integer(), server_default='25', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('nearby_radius_km')


    # ### end Alembic commands ###
