"""add promo campaigns and redemptions

Revision ID: c06796ada409
Revises: 20260528_trainer_interests
Create Date: 2026-06-02 18:01:47.466233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06796ada409'
down_revision: Union[str, Sequence[str], None] = '20260528_trainer_interests'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('benefit_type', sa.String(length=30), nullable=False),
    sa.Column('benefit_value', sa.Integer(), nullable=True),
    sa.Column('benefit_duration_months', sa.Integer(), nullable=True),
    sa.Column('reward_type', sa.String(length=30), nullable=True),
    sa.Column('reward_value', sa.Integer(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ios_offer_code', sa.String(length=80), nullable=True),
    sa.Column('android_promo_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_campaigns_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_promo_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_campaigns_created_by_admin_id'), ['created_by_admin_id'], unique=False)
        batch_op.create_index('ix_promo_campaigns_owner_status', ['owner_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_campaigns_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_campaigns_status'), ['status'], unique=False)
        batch_op.create_index('ix_promo_campaigns_status_valid', ['status', 'valid_until'], unique=False)

    op.create_table('promo_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('store_transaction_id', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['promo_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_promo_redemptions_campaign_user')
    )
    with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_redemptions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index('ix_promo_redemptions_campaign_status', ['campaign_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_redemptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_redemptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_redemptions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_promo_redemptions_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_redemptions', schema=None) as batch_op:
        batch_op.drop_index('ix_promo_redemptions_user_status')
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_status'))
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_created_at'))
        batch_op.drop_index('ix_promo_redemptions_campaign_status')
        batch_op.drop_index(batch_op.f('ix_promo_redemptions_campaign_id'))

    op.drop_table('promo_redemptions')
    with op.batch_alter_table('promo_campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_promo_campaigns_status_valid')
        batch_op.drop_index(batch_op.f('ix_promo_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_promo_campaigns_owner_user_id'))
        batch_op.drop_index('ix_promo_campaigns_owner_status')
        batch_op.drop_index(batch_op.f('ix_promo_campaigns_created_by_admin_id'))
        batch_op.drop_index(batch_op.f('ix_promo_campaigns_created_at'))
        batch_op.drop_index(batch_op.f('ix_promo_campaigns_code'))

    op.drop_table('promo_campaigns')
    # ### end Alembic commands ###
