"""add messages table

Revision ID: cc9328369424
Revises: bfd2fc27f1bc
Create Date: 2026-03-15 15:51:36.872586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9328369424'
down_revision: Union[str, Sequence[str], None] = 'bfd2fc27f1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(recipient_user_id IS NOT NULL AND group_id IS NULL) OR (recipient_user_id IS NULL AND group_id IS NOT NULL)', name='ck_messages_private_xor_group'),
    sa.CheckConstraint('length(content) >= 1', name='ck_messages_content_non_empty'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_group_id'), ['group_id'], unique=False)
        batch_op.create_index('ix_messages_group_thread', ['group_id', 'created_at'], unique=False)
        batch_op.create_index('ix_messages_private_thread', ['sender_user_id', 'recipient_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_user_id'), ['sender_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_user_id'))
        batch_op.drop_index('ix_messages_private_thread')
        batch_op.drop_index('ix_messages_group_thread')
        batch_op.drop_index(batch_op.f('ix_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    # ### end Alembic commands ###
